version: "3.8"

services:
  instivo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instivo-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:3333
