services:
  instivo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instivo-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3333
    networks:
      - instivo-network

networks:
  instivo-network:
    driver: bridge
