openapi: 3.0.0
paths:
  /:
    post:
      operationId: AppController_createSalario
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSalarioDto'
      responses:
        '201':
          description: ''
      tags: &ref_0
        - App
  /registros:
    get:
      operationId: AppController_findAllSalarios
      parameters:
        - name: dataAdmissaoInicio
          required: true
          in: query
          description: Data de admissão do funcionário
          schema:
            format: date-time
            example: '2025-01-01'
            type: string
        - name: dataAdmissaoFim
          required: true
          in: query
          description: Data de admissão do funcionário
          schema:
            format: date-time
            example: '2025-01-01'
            type: string
        - name: salarioBrutoInicio
          required: true
          in: query
          description: Salário bruto do funcionário
          schema:
            example: 2000
            type: number
        - name: salarioBrutoFim
          required: true
          in: query
          description: Salário bruto do funcionário
          schema:
            example: 2000
            type: number
        - name: page
          required: true
          in: query
          description: Página
          schema:
            example: 1
            type: number
        - name: limit
          required: true
          in: query
          description: Limite
          schema:
            example: 10
            type: number
      responses:
        '200':
          description: ''
      tags: *ref_0
  /registros/{id}:
    get:
      operationId: AppController_findSalarioById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_0
info:
  title: Expo API Template
  description: The expo API template
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateSalarioDto:
      type: object
      properties:
        dataAdmissao:
          format: date-time
          type: string
          description: Data de admissão do funcionário
          example: '2025-01-01'
        salarioBruto:
          type: number
          description: Salário bruto do funcionário
          example: 2000
      required:
        - dataAdmissao
        - salarioBruto
